import { ICON_NAMES } from "@/components/Icon";
import { formatDate, formatRange, passPercent, rupees } from "@/lib/format";
import { COMMITTEES, DOC_CATEGORIES, EVENT_TYPES, FACILITY_CATEGORIES } from "@/lib/types";
import type { Field } from "./fields";

// Every list the admin panel can edit. Each entry drives a list page (/admin/<key>) and a form (/admin/<key>/<id>).

type Row = Record<string, unknown>;
export type Column = { name: string; label: string; format?: (row: Row) => string };

export type Resource = {
  key: string;
  table: string;
  label: string;
  singular: string;
  intro?: string;
  fields: Field[];
  columns: Column[];
  /** Ordering for the list (the public site uses the same). */
  order: [string, boolean][];
  /** Rows can be moved up and down (table has a sort column). */
  sortable?: boolean;
  /** Table has a published flag that can be toggled from the list. */
  publishable?: boolean;
  /** Filter tabs on the list page. */
  filter?: { field: string; label: string; options?: [string, string][] };
  /** Columns that hold uploaded files, removed from storage when replaced or deleted. */
  files?: string[];
  defaults?: Row;
  /** Extra checks before saving; return an error message to stop the save. */
  validate?: (row: Row) => string | null;
};

const opts = (o: Record<string, string>): [string, string][] => Object.entries(o);
const yesNo = (v: unknown) => (v ? "Yes" : "No");
const iconField: Field = { name: "icon", label: "Icon", type: "icon", options: ICON_NAMES.map((n) => [n, n]), half: true };
const published: Field = { name: "published", label: "Show on the website", type: "checkbox" };

export const RESOURCES: Resource[] = [
  {
    key: "slides",
    table: "slides",
    label: "Hero slider",
    singular: "slide",
    intro: "The large photos that rotate at the top of the home page. Use landscape photos about 1600px wide.",
    fields: [
      { name: "image", label: "Photo", type: "image", required: true },
      { name: "alt", label: "Describe the photo (for screen readers)", type: "text", required: true },
      { name: "kicker", label: "Small line above the heading", type: "text", half: true },
      { name: "heading", label: "Heading", type: "text", required: true, half: true },
      { name: "link", label: "\"Know More\" button link", type: "url", placeholder: "/about", half: true },
      { name: "position", label: "Photo focus (CSS position)", type: "text", placeholder: "center", help: "Which part of the photo stays visible when it's cropped, e.g. \"center 40%\".", half: true },
      published,
    ],
    columns: [{ name: "heading", label: "Heading" }, { name: "kicker", label: "Kicker" }],
    order: [["sort", true]],
    sortable: true,
    publishable: true,
    files: ["image"],
    defaults: { position: "center", published: true },
  },
  {
    key: "announcements",
    table: "announcements",
    label: "Notices & ticker",
    singular: "notice",
    intro: "Short notices for the scrolling ticker and the home-page notice board: circulars, holiday notices, upcoming exams. A pinned notice is also shown as the featured notice on the home page.",
    fields: [
      { name: "title", label: "Notice", type: "text", required: true },
      { name: "text", label: "Details (shown on the featured notice)", type: "textarea" },
      { name: "date", label: "Date", type: "date", half: true },
      { name: "expires_on", label: "Hide after", type: "date", half: true, help: "Leave empty to keep it until you remove it." },
      { name: "link", label: "Link to a page", type: "url", placeholder: "/admissions", half: true },
      { name: "file_url", label: "Or attach a PDF", type: "pdf", half: true },
      { name: "pinned", label: "Pin as the featured notice", type: "checkbox" },
      published,
    ],
    columns: [{ name: "title", label: "Notice" }, { name: "date", label: "Date", format: (r) => formatDate(r.date as string) }, { name: "pinned", label: "Pinned", format: (r) => yesNo(r.pinned) }],
    order: [["pinned", false], ["date", false]],
    publishable: true,
    files: ["file_url"],
    defaults: { published: true },
  },
  {
    key: "documents",
    table: "documents",
    label: "Documents & PDFs",
    singular: "document",
    intro: "Every downloadable PDF: circulars, CBSE circulars, syllabus, study material, forms, policies, fee and calendar PDFs, date sheets and results. The category decides where it appears on the site.",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "category", label: "Category", type: "select", required: true, options: opts(DOC_CATEGORIES), half: true },
      { name: "date", label: "Date", type: "date", half: true },
      { name: "file_url", label: "PDF file", type: "pdf", required: true },
      { name: "class_name", label: "Class", type: "text", placeholder: "e.g. Class X", half: true },
      { name: "subject", label: "Subject", type: "text", half: true },
      { name: "description", label: "Short description", type: "textarea" },
      published,
    ],
    columns: [
      { name: "title", label: "Title" },
      { name: "category", label: "Category", format: (r) => DOC_CATEGORIES[r.category as keyof typeof DOC_CATEGORIES] ?? String(r.category) },
      { name: "date", label: "Date", format: (r) => formatDate(r.date as string) },
    ],
    order: [["date", false], ["sort", true]],
    publishable: true,
    filter: { field: "category", label: "Category", options: opts(DOC_CATEGORIES) },
    files: ["file_url"],
    defaults: { category: "circular", published: true },
  },
  {
    key: "fees",
    table: "fee_structure",
    label: "Fee structure",
    singular: "fee item",
    intro: "One row per class group and fee head, e.g. \"Classes I–V · Tuition fee · ₹2,500 · Monthly\". The website shows a table per session. Use \"Copy session\" to start a new year from last year's fees.",
    fields: [
      { name: "session", label: "Session", type: "text", required: true, placeholder: "2026-27", half: true },
      { name: "class_group", label: "Class / class group", type: "text", required: true, placeholder: "Classes I–V", half: true },
      { name: "fee_head", label: "Fee head", type: "text", required: true, placeholder: "Tuition fee", half: true },
      { name: "amount", label: "Amount (₹)", type: "number", required: true, half: true },
      { name: "frequency", label: "Frequency", type: "select", options: [["Monthly", "Monthly"], ["Quarterly", "Quarterly"], ["Half-yearly", "Half-yearly"], ["Annual", "Annual"], ["One-time", "One-time"]], half: true },
    ],
    columns: [
      { name: "session", label: "Session" },
      { name: "class_group", label: "Class" },
      { name: "fee_head", label: "Fee head" },
      { name: "amount", label: "Amount", format: (r) => `${rupees(r.amount as number)} · ${r.frequency}` },
    ],
    order: [["session", false], ["sort", true]],
    sortable: true,
    filter: { field: "session", label: "Session" },
    defaults: { frequency: "Annual" },
  },
  {
    key: "results",
    table: "board_results",
    label: "Board results",
    singular: "result",
    intro: "Class X and XII board results by year. Pass percentage is calculated for you. The disclosure page shows the last three years.",
    fields: [
      { name: "class", label: "Class", type: "select", required: true, options: [["X", "Class X"], ["XII", "Class XII"]], half: true },
      { name: "year", label: "Year", type: "text", required: true, placeholder: "2026", half: true },
      { name: "registered", label: "No. of registered students", type: "number", required: true, half: true },
      { name: "passed", label: "No. of students passed", type: "number", required: true, half: true },
      { name: "remarks", label: "Remarks", type: "text" },
    ],
    columns: [
      { name: "class", label: "Class" },
      { name: "year", label: "Year" },
      { name: "registered", label: "Registered" },
      { name: "passed", label: "Passed" },
      { name: "pct", label: "Pass %", format: (r) => passPercent(r.registered as number, r.passed as number) },
    ],
    order: [["class", true], ["year", false]],
    filter: { field: "class", label: "Class", options: [["X", "Class X"], ["XII", "Class XII"]] },
    defaults: { class: "X" },
    validate: (r) => (Number(r.passed) > Number(r.registered) ? "Passed students can't be more than registered students." : null),
  },
  {
    key: "calendar",
    table: "calendar_events",
    label: "Academic calendar",
    singular: "date",
    intro: "Holidays, exams, result days, parent-teacher meetings, admission dates and events. These feed the Academic Calendar, Examination Schedule, PTM, Important Dates and the home-page notice board.",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "type", label: "Type", type: "select", required: true, options: opts(EVENT_TYPES), half: true },
      { name: "session", label: "Session", type: "text", placeholder: "2026-27", half: true },
      { name: "start_date", label: "Date (or first day)", type: "date", required: true, half: true },
      { name: "end_date", label: "Last day (if more than one day)", type: "date", half: true },
      { name: "description", label: "Details", type: "textarea" },
      published,
    ],
    columns: [
      { name: "title", label: "Title" },
      { name: "type", label: "Type", format: (r) => EVENT_TYPES[r.type as keyof typeof EVENT_TYPES] },
      { name: "start_date", label: "When", format: (r) => formatRange(r.start_date as string, r.end_date as string | null) },
    ],
    order: [["start_date", true]],
    publishable: true,
    filter: { field: "type", label: "Type", options: opts(EVENT_TYPES) },
    defaults: { type: "event", published: true },
  },
  {
    key: "committees",
    table: "committee_members",
    label: "Committees",
    singular: "member",
    intro: "Management committee, School Management Committee (SMC), Parent Teacher Association (PTA) and Student Council. SMC and PTA lists appear on the Mandatory Public Disclosure page.",
    fields: [
      { name: "committee", label: "Committee", type: "select", required: true, options: opts(COMMITTEES) },
      { name: "name", label: "Name", type: "text", required: true, half: true },
      { name: "designation", label: "Designation", type: "text", placeholder: "Chairperson / Member / Head Girl", half: true },
      { name: "representing", label: "Representing / class", type: "text", placeholder: "Parent representative, teacher, Class XII…" },
      { name: "photo", label: "Photo (optional)", type: "image" },
    ],
    columns: [{ name: "name", label: "Name" }, { name: "designation", label: "Designation" }, { name: "committee", label: "Committee", format: (r) => COMMITTEES[r.committee as keyof typeof COMMITTEES] }],
    order: [["committee", true], ["sort", true]],
    sortable: true,
    filter: { field: "committee", label: "Committee", options: opts(COMMITTEES) },
    files: ["photo"],
    defaults: { committee: "smc" },
  },
  {
    key: "facilities",
    table: "facilities",
    label: "Facilities",
    singular: "facility",
    intro: "Cards on the Campus pages. Featured facilities with a photo show as large photo cards.",
    fields: [
      { name: "title", label: "Title", type: "text", required: true, half: true },
      { name: "category", label: "Page", type: "select", required: true, options: opts(FACILITY_CATEGORIES), half: true },
      { name: "text", label: "Description", type: "textarea" },
      { name: "stat", label: "Number to highlight", type: "text", placeholder: "4,000", half: true },
      { name: "unit", label: "Unit", type: "text", placeholder: "books", half: true },
      iconField,
      { name: "image", label: "Photo", type: "image" },
      { name: "featured", label: "Featured (large photo card)", type: "checkbox" },
      published,
    ],
    columns: [{ name: "title", label: "Title" }, { name: "category", label: "Page", format: (r) => FACILITY_CATEGORIES[r.category as keyof typeof FACILITY_CATEGORIES] }],
    order: [["sort", true]],
    sortable: true,
    publishable: true,
    filter: { field: "category", label: "Page", options: opts(FACILITY_CATEGORIES) },
    files: ["image"],
    defaults: { category: "other", icon: "building", published: true },
  },
  {
    key: "transport",
    table: "transport_routes",
    label: "Bus routes",
    singular: "route",
    fields: [
      { name: "route_no", label: "Route", type: "text", required: true, placeholder: "Route 1", half: true },
      { name: "contact", label: "Driver / attendant contact", type: "text", half: true },
      { name: "areas", label: "Areas covered", type: "textarea", required: true },
    ],
    columns: [{ name: "route_no", label: "Route" }, { name: "areas", label: "Areas" }],
    order: [["sort", true]],
    sortable: true,
  },
  {
    key: "facts",
    table: "facts",
    label: "Numbers band",
    singular: "number",
    intro: "The counting numbers on the home page.",
    fields: [
      { name: "value", label: "Number", type: "text", required: true, half: true },
      { name: "suffix", label: "After the number", type: "text", placeholder: "+", half: true },
      { name: "label", label: "Label", type: "text", required: true, half: true },
      iconField,
    ],
    columns: [{ name: "value", label: "Number", format: (r) => `${r.value}${r.suffix}` }, { name: "label", label: "Label" }],
    order: [["sort", true]],
    sortable: true,
    defaults: { icon: "star" },
  },
  {
    key: "values",
    table: "core_values",
    label: "Core values",
    singular: "value",
    fields: [{ name: "title", label: "Value", type: "text", required: true, half: true }, iconField, { name: "text", label: "Description", type: "textarea", required: true }],
    columns: [{ name: "title", label: "Value" }, { name: "text", label: "Description" }],
    order: [["sort", true]],
    sortable: true,
    defaults: { icon: "star" },
  },
  {
    key: "timeline",
    table: "timeline",
    label: "History timeline",
    singular: "milestone",
    fields: [
      { name: "year", label: "Year", type: "text", required: true, half: true },
      { name: "title", label: "Title", type: "text", required: true, half: true },
      { name: "text", label: "Description", type: "textarea" },
    ],
    columns: [{ name: "year", label: "Year" }, { name: "title", label: "Title" }],
    order: [["sort", true]],
    sortable: true,
  },
  {
    key: "stages",
    table: "stages",
    label: "School stages",
    singular: "stage",
    intro: "Pre-primary to Senior Secondary, with the subjects taught at each stage (Curriculum and Subjects Offered pages).",
    fields: [
      { name: "title", label: "Stage", type: "text", required: true, half: true },
      { name: "classes", label: "Classes", type: "text", placeholder: "Classes I–V", half: true },
      { name: "text", label: "Description", type: "textarea" },
      { name: "subjects", label: "Subjects (one per line)", type: "list" },
    ],
    columns: [{ name: "title", label: "Stage" }, { name: "classes", label: "Classes" }],
    order: [["sort", true]],
    sortable: true,
  },
  {
    key: "streams",
    table: "streams",
    label: "Class XI streams",
    singular: "stream",
    fields: [
      { name: "name", label: "Stream", type: "text", required: true, half: true },
      { name: "min", label: "Minimum % in Class X", type: "number", half: true },
      { name: "need", label: "Eligibility", type: "text", placeholder: "80% overall in Class X, with at least 70% in Maths" },
      { name: "subjects", label: "Subjects", type: "textarea" },
    ],
    columns: [{ name: "name", label: "Stream" }, { name: "min", label: "Minimum %" }],
    order: [["sort", true]],
    sortable: true,
  },
  {
    key: "admission-steps",
    table: "admission_steps",
    label: "Admission steps",
    singular: "step",
    fields: [{ name: "title", label: "Step", type: "text", required: true }, { name: "text", label: "Description", type: "textarea" }],
    columns: [{ name: "title", label: "Step" }],
    order: [["sort", true]],
    sortable: true,
  },
  {
    key: "clubs",
    table: "clubs",
    label: "Clubs & societies",
    singular: "club",
    fields: [{ name: "name", label: "Club", type: "text", required: true }, { name: "description", label: "Description", type: "textarea" }],
    columns: [{ name: "name", label: "Club" }],
    order: [["sort", true]],
    sortable: true,
  },
  {
    key: "events",
    table: "events",
    label: "Events & celebrations",
    singular: "event",
    fields: [
      { name: "title", label: "Title", type: "text", required: true, half: true },
      { name: "kind", label: "Type", type: "select", options: [["event", "School event"], ["celebration", "Celebration / festival"]], half: true },
      { name: "text", label: "Description", type: "textarea" },
      { name: "date", label: "Date", type: "date", half: true },
      iconField,
      { name: "image", label: "Photo", type: "image" },
      published,
    ],
    columns: [{ name: "title", label: "Title" }, { name: "kind", label: "Type" }, { name: "date", label: "Date", format: (r) => formatDate(r.date as string) }],
    order: [["sort", true]],
    sortable: true,
    publishable: true,
    filter: { field: "kind", label: "Type", options: [["event", "School events"], ["celebration", "Celebrations"]] },
    files: ["image"],
    defaults: { kind: "event", icon: "star", published: true },
  },
  {
    key: "achievements",
    table: "achievements",
    label: "Achievements",
    singular: "achievement",
    fields: [
      { name: "title", label: "Title", type: "text", required: true, half: true },
      { name: "tag", label: "Year or tag", type: "text", placeholder: "2026", half: true },
      { name: "category", label: "Category", type: "select", options: [["academic", "Academic"], ["sports", "Sports"], ["co_curricular", "Co-curricular"]] },
      { name: "text", label: "Description", type: "textarea", required: true },
      { name: "image", label: "Photo", type: "image" },
      published,
    ],
    columns: [{ name: "title", label: "Title" }, { name: "tag", label: "Tag" }, { name: "category", label: "Category" }],
    order: [["sort", true]],
    sortable: true,
    publishable: true,
    files: ["image"],
    defaults: { category: "academic", published: true },
  },
  {
    key: "albums",
    table: "gallery_albums",
    label: "Photo albums",
    singular: "album",
    intro: "Create an album, save it, then add photos to it.",
    fields: [
      { name: "title", label: "Album title", type: "text", required: true, half: true },
      { name: "slug", label: "Web address", type: "text", required: true, placeholder: "annual-day-2026", help: "Lowercase letters, numbers and dashes. The album appears at /gallery/<web address>.", half: true },
      { name: "date", label: "Date", type: "date", half: true },
      { name: "cover", label: "Cover photo", type: "image" },
      { name: "description", label: "Description", type: "textarea" },
      published,
    ],
    columns: [{ name: "title", label: "Album" }, { name: "date", label: "Date", format: (r) => formatDate(r.date as string) }],
    order: [["sort", true], ["date", false]],
    sortable: true,
    publishable: true,
    files: ["cover"],
    defaults: { published: true },
    validate: (r) => (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(String(r.slug)) ? "Web address can only use lowercase letters, numbers and dashes." : r.slug === "videos" ? "\"videos\" is reserved. Choose another web address." : null),
  },
  {
    key: "videos",
    table: "videos",
    label: "Videos",
    singular: "video",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "url", label: "YouTube link", type: "url", required: true, placeholder: "https://www.youtube.com/watch?v=…", half: true },
      { name: "date", label: "Date", type: "date", half: true },
      published,
    ],
    columns: [{ name: "title", label: "Title" }, { name: "url", label: "Link" }],
    order: [["sort", true], ["date", false]],
    sortable: true,
    publishable: true,
    defaults: { published: true },
  },
  {
    key: "notable-alumni",
    table: "notable_alumni",
    label: "Notable alumni",
    singular: "alumna",
    fields: [
      { name: "name", label: "Name", type: "text", required: true, half: true },
      { name: "batch", label: "Batch (year)", type: "text", half: true },
      { name: "title", label: "Now", type: "text", placeholder: "Surgeon, AIIMS Delhi" },
      { name: "text", label: "Story", type: "textarea" },
      { name: "photo", label: "Photo", type: "image" },
      published,
    ],
    columns: [{ name: "name", label: "Name" }, { name: "batch", label: "Batch" }],
    order: [["sort", true]],
    sortable: true,
    publishable: true,
    files: ["photo"],
    defaults: { published: true },
  },
  {
    key: "alumni-events",
    table: "alumni_events",
    label: "Alumni events",
    singular: "alumni event",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "date", label: "Date", type: "date", half: true },
      { name: "venue", label: "Venue", type: "text", half: true },
      { name: "text", label: "Details", type: "textarea" },
      { name: "image", label: "Photo", type: "image" },
      published,
    ],
    columns: [{ name: "title", label: "Title" }, { name: "date", label: "Date", format: (r) => formatDate(r.date as string) }],
    order: [["date", false]],
    publishable: true,
    files: ["image"],
    defaults: { published: true },
  },
  {
    key: "vacancies",
    table: "vacancies",
    label: "Job vacancies",
    singular: "vacancy",
    fields: [
      { name: "post", label: "Post", type: "text", required: true, placeholder: "PGT Chemistry", half: true },
      { name: "department", label: "Department", type: "text", half: true },
      { name: "qualification", label: "Qualification", type: "textarea" },
      { name: "experience", label: "Experience", type: "text", half: true },
      { name: "last_date", label: "Last date to apply", type: "date", half: true },
      { name: "description", label: "Job description", type: "textarea" },
      { name: "is_open", label: "Open for applications", type: "checkbox" },
    ],
    columns: [{ name: "post", label: "Post" }, { name: "last_date", label: "Last date", format: (r) => formatDate(r.last_date as string) }, { name: "is_open", label: "Open", format: (r) => yesNo(r.is_open) }],
    order: [["sort", true]],
    sortable: true,
    defaults: { is_open: true },
  },
];

export const getResource = (key: string) => RESOURCES.find((r) => r.key === key);
